id: I4D1F11FA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T21:02:56+00:00'
last_modified: '2022-06-09T04:41:26.515271+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16455
  title: འགྲེལ་པ་དོན་གསལ་དང་། རྣམ་བཤད་སྙིང་པོ་རྒྱན་གྱི་དགོངས་འགྲེལ་ཚིག་དོན་རབ་གསལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    84B4:
      image_group_id: I1KG16457
      title: Volume 1 of 'grel pa don gsal dang / rnam bshad snying po rgyan gyi dgongs
        'grel tshig don rab gsal/
      total_pages: 444
      order: 1
      base_file: 84B4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
