id: P007083
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG16455
  title: འགྲེལ་པ་དོན་གསལ་དང་། རྣམ་བཤད་སྙིང་པོ་རྒྱན་གྱི་དགོངས་འགྲེལ་ཚིག་དོན་རབ་གསལ།
  author: ''
  volumes:
    df151712c50b4bdd9396c27fee21acc8:
      image_group_id: I1KG16457
      title: Volume 1 of 'grel pa don gsal dang / rnam bshad snying po rgyan gyi dgongs
        'grel tshig don rab gsal/
      volume_number: 1
      total_pages: 444
      base_file: v001.txt
