id: P007083
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16455
  title: འགྲེལ་པ་དོན་གསལ་དང་། རྣམ་བཤད་སྙིང་པོ་རྒྱན་གྱི་དགོངས་འགྲེལ་ཚིག་དོན་རབ་གསལ།
  author: ''
  volumes:
    c5f6b104ba994cd5a6ceceddb0293d1b:
      image_group_id: I1KG16457
      title: ''
      volume_number: 1
      total_pages: 444
ebook_metadata:
  title: འགྲེལ་པ་དོན་གསལ་དང་། རྣམ་བཤད་སྙིང་པོ་རྒྱན་གྱི་དགོངས་འགྲེལ་ཚིག་དོན་རབ་གསལ།
  author: ''
  sku: P007083
  cover: cover.jpg
  layers:
  - pagination
